(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],cash=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),KEY='pontoflex-vanilla-v1';
const seed={nome:'',cpf:'',cargo:'',empresa:'',cnpj:'',cep:'',endereco:'',telefone:'',salario:0,divisor:220,jornada:8,adicionalNoturno:20,vt:6,vr:5,adiantamento:0,outros:0,inss:true,registros:[],funcionarioImagem:'',empresaImagem:'',funcionarioFit:'cover',funcionarioZoom:100,funcionarioX:50,funcionarioY:50,empresaFit:'contain',empresaZoom:100,empresaX:50,empresaY:50};
let state=load(),editing=null,tab='jornada',competencia=currentCompetency();
function load(){try{return{...seed,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{...seed}}}function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function currentCompetency(){let d=new Date();if(d.getDate()>25)d.setMonth(d.getMonth()+1);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function range(){let[y,m]=competencia.split('-').map(Number),a=new Date(y,m-2,26,12),b=new Date(y,m-1,25,12),iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return{start:iso(a),end:iso(b),label:`${a.toLocaleDateString('pt-BR')} a ${b.toLocaleDateString('pt-BR')}`}}
const mins=v=>v?+v.slice(0,2)*60+ +v.slice(3):0;function elapsed(a,b){if(!a||!b)return 0;let x=mins(a),y=mins(b);if(y<=x)y+=1440;return y-x}function worked(e){return['worked','holiday'].includes(e.status)?e.intervals.reduce((n,i)=>n+elapsed(i.in,i.out),0):0}
function inss(base){let t=0,p=0;for(const[l,r]of[[1621,.075],[2902.84,.09],[4354.27,.12],[8475.55,.14]]){t+=Math.max(0,Math.min(base,l)-p)*r;p=l;if(base<=l)break}return t}
function summary(){let reg=0,e50=0,e100=0,diarias=0,faltas=0;entries().forEach(e=>{diarias+=+e.diaria||0;if(e.status==='absence')faltas++;let total=worked(e),extra=Math.max(0,total-state.jornada*60);reg+=Math.min(total,state.jornada*60);e.extra==100?e100+=extra:e50+=extra});let hora=state.salario/state.divisor||0,he50=e50/60*hora*1.5,he100=e100/60*hora*2,falta=state.salario/30*faltas,bruto=state.salario+he50+he100+diarias,base=Math.max(0,bruto-falta-diarias),ins=state.inss?inss(base):0,vt=state.salario*state.vt/100,vr=state.salario*state.vr/100,descontos=falta+ins+vt+vr+state.adiantamento+state.outros;return{reg,e50,e100,diarias,faltas,hora,he50,he100,falta,bruto,base,ins,vt,vr,descontos,liquido:bruto-descontos}}
function entries(){let r=range();return state.registros.filter(e=>e.data>=r.start&&e.data<=r.end).sort((a,b)=>b.data.localeCompare(a.data))}
function render(){save();$('#mes').value=competencia;$('#periodo').textContent=range().label;let s=summary();$('#metricas').innerHTML=[['Salário base',cash.format(state.salario)],['Horas normais',(s.reg/60).toFixed(1)+'h'],['Horas extras',((s.e50+s.e100)/60).toFixed(1)+'h'],['Diárias',cash.format(s.diarias)],['Líquido estimado',cash.format(s.liquido)]].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');let es=entries();$('#qtdDias').textContent=`${es.length} dias`;$('#registros').innerHTML=es.length?es.map(e=>`<article class="entry"><time>${new Date(e.data+'T12:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</time><div><strong>${labels[e.status]} ${e.diaria?`<mark class="daily">${cash.format(e.diaria)}</mark>`:''}</strong><small>${e.intervals.map((i,n)=>`${n+1}º ${i.in||'—'}–${i.out||'—'}`).join(' · ')} · ${(worked(e)/60).toFixed(2)}h</small></div><div class="entry-actions"><button data-edit="${e.id}">Editar</button><button class="danger" data-del="${e.id}">Excluir</button></div></article>`).join(''):'<div class="empty"><h3>Nenhum registro</h3><p>Adicione um dia para iniciar os cálculos.</p></div>';renderPaycheck(s);fillFields()}
const labels={worked:'Trabalhado',dayoff:'Folga',absence:'Falta',certificate:'Atestado',vacation:'Férias',holiday:'Feriado trabalhado'};
function renderPaycheck(s){let rows=[['Salário mensal',state.divisor+'h',state.salario,0],['Hora extra 50%',(s.e50/60).toFixed(2)+'h',s.he50,0],['Hora extra 100%',(s.e100/60).toFixed(2)+'h',s.he100,0],['Faltas',s.faltas+' dia(s)',0,s.falta],['INSS','Tabela 2026',0,s.ins],['Vale-transporte',state.vt+'%',0,s.vt],['Vale-refeição',state.vr+'%',0,s.vr],['Adiantamento','Valor fixo',0,state.adiantamento],['Outros descontos','Informado',0,state.outros]];if(s.diarias)rows.splice(3,0,['Diárias','Competência',s.diarias,0]);$('#holerite').innerHTML=`<div class="payhead"><div><em>PONTOFLEX</em><h2>Demonstrativo de pagamento</h2></div><b>${range().label}</b></div><div class="company"><p><span>Empresa</span><b>${state.empresa||'Não informada'}</b></p><p><span>CNPJ</span><b>${state.cnpj||'—'}</b></p><p><span>Endereço</span><b>${state.endereco||'—'}</b></p></div><div class="person"><p><span>Funcionário</span><b>${state.nome||'Não informado'}</b></p><p><span>CPF</span><b>${state.cpf||'—'}</b></p><p><span>Cargo</span><b>${state.cargo||'—'}</b></p></div><table><thead><tr><th>Descrição</th><th>Referência</th><th>Proventos</th><th>Descontos</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]?cash.format(r[2]):''}</td><td>${r[3]?cash.format(r[3]):''}</td></tr>`).join('')}</tbody></table><div class="totals"><p><span>Proventos</span><b>${cash.format(s.bruto)}</b></p><p><span>Descontos</span><b>${cash.format(s.descontos)}</b></p><p class="net"><span>Valor líquido</span><b>${cash.format(s.liquido)}</b></p></div><p>Local e data: __________________________________, ____/____/________</p><div class="signatures"><div>${state.nome||'Funcionário'}<small>Assinatura do funcionário</small></div><div>${state.empresa||'Empresa'}<small>Assinatura da empresa</small></div></div>`}
function fillFields(){$$('[data-field]').forEach(el=>{let k=el.dataset.field;el.type==='checkbox'?el.checked=!!state[k]:el.value=state[k]??''});renderImages()}
function imageStyle(prefix){return`object-fit:${state[prefix+'Fit']};object-position:${state[prefix+'X']}% ${state[prefix+'Y']}%;transform:scale(${state[prefix+'Zoom']/100})`}
function renderImages(){[['funcionario','funcionarioImagem'],['empresa','empresaImagem']].forEach(([prefix,key])=>{const id=prefix==='funcionario'?'#previewFuncionario':'#previewEmpresa',box=$(id),src=state[key];box.innerHTML=src?`<img src="${src}" alt="Pré-visualização" style="${imageStyle(prefix)}">`:`<span>Sem ${prefix==='funcionario'?'foto':'imagem'}</span>`});$$('[data-image-prop]').forEach(el=>{const key=el.dataset.imageProp;el.value=state[key];const out=$(`[data-output="${key}"]`);if(out)out.value=state[key]+'%'});const old=$('.company-layout-frame');if(old)old.remove();if(state.empresaImagem)$('#holerite').insertAdjacentHTML('afterbegin',`<div class="company-layout-frame"><img class="company-layout-image" src="${state.empresaImagem}" alt="Layout da empresa" style="${imageStyle('empresa')}"></div>`)}
function openModal(entry){editing=entry||{id:crypto.randomUUID(),data:new Date().toISOString().slice(0,10),status:'worked',intervals:[{in:'08:00',out:'12:00'},{in:'13:00',out:'17:00'}],extra:50,diaria:0,observacao:''};$('#data').value=editing.data;$('#situacao').value=editing.status;$('#tipoExtra').value=editing.extra;$('#diaria').value=editing.diaria||'';$('#observacao').value=editing.observacao||'';renderIntervals();$('#modal').showModal()}
function renderIntervals(){$('#intervalos').innerHTML=editing.intervals.map((i,n)=>`<div class="interval-row"><label>Entrada ${n+1}<input type="time" data-in="${n}" value="${i.in}"></label><label>Saída ${n+1}<input type="time" data-out="${n}" value="${i.out}"></label>${editing.intervals.length>1?`<button type="button" class="remove" data-remove="${n}">×</button>`:''}</div>`).join('')}
function setTab(id){tab=id;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$('#titulo').textContent=id==='jornada'?'Minha jornada':id==='contracheque'?'Contracheque':'Configurações';$('#novo').hidden=id!=='jornada';$('#competencia').hidden=id==='configuracoes';scrollTo(0,0)}
function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}function base(type){let n=(state.nome||'funcionario').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\W+/g,'-');return`${n}-${competencia}-${type}`}
$$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#novo').onclick=()=>openModal();$('#mes').onchange=e=>{competencia=e.target.value;render()};$('#mesAnterior').onclick=()=>shift(-1);$('#mesSeguinte').onclick=()=>shift(1);function shift(n){let[y,m]=competencia.split('-'),d=new Date(y,+m-1+n,1);competencia=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;render()}
$('#registros').onclick=e=>{let edit=e.target.dataset.edit,del=e.target.dataset.del;if(edit)openModal(state.registros.find(x=>x.id===edit));if(del&&confirm('Excluir este registro?')){state.registros=state.registros.filter(x=>x.id!==del);render()}};$('#intervalos').oninput=e=>{let n=e.target.dataset.in??e.target.dataset.out;if(n!==undefined)editing.intervals[n][e.target.dataset.in!==undefined?'in':'out']=e.target.value};$('#intervalos').onclick=e=>{if(e.target.dataset.remove!==undefined){editing.intervals.splice(+e.target.dataset.remove,1);renderIntervals()}};$('#adicionarIntervalo').onclick=()=>{if(editing.intervals.length<6){editing.intervals.push({in:'',out:''});renderIntervals()}};
$('#salvarRegistro').onclick=()=>{editing={...editing,data:$('#data').value,status:$('#situacao').value,extra:+$('#tipoExtra').value,diaria:+$('#diaria').value||0,observacao:$('#observacao').value};let bad=['worked','holiday'].includes(editing.status)&&editing.intervals.some(i=>!i.in||!i.out);if(!editing.data||bad){$('#erros').textContent='Preencha a data e todos os pares de entrada e saída.';return}state.registros=[...state.registros.filter(x=>x.id!==editing.id),editing];$('#modal').close();render()};
$$('[data-field]').forEach(el=>el.oninput=async e=>{let k=e.target.dataset.field,v=e.target.type==='checkbox'?e.target.checked:e.target.type==='number'?+e.target.value:e.target.value;if(k==='cpf')v=v.replace(/\D/g,'').slice(0,11).replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2');if(k==='cnpj')v=v.replace(/\D/g,'').slice(0,14).replace(/(\d{2})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1/$2').replace(/(\d{4})(\d{1,2})$/,'$1-$2');if(k==='cep'){v=v.replace(/\D/g,'').slice(0,8).replace(/(\d{5})(\d)/,'$1-$2');if(v.replace(/\D/g,'').length===8)lookupCep(v)}state[k]=v;e.target.value=v;render()});async function lookupCep(v){$('#cepStatus').textContent='Buscando endereço...';try{let r=await fetch(`https://viacep.com.br/ws/${v.replace(/\D/g,'')}/json/`),j=await r.json();if(j.erro)throw 0;state.endereco=[j.logradouro,j.bairro,`${j.localidade} - ${j.uf}`].filter(Boolean).join(', ');$('#cepStatus').textContent='Endereço preenchido automaticamente.';render()}catch{$('#cepStatus').textContent='CEP não encontrado ou sem conexão.'}}
$('#exportar').onclick=()=>download(base('backup')+'.json',JSON.stringify(state,null,2),'application/json');$('#importar').onclick=()=>$('#arquivo').click();$('#arquivo').onchange=async e=>{try{state={...seed,...JSON.parse(await e.target.files[0].text())};render()}catch{alert('Backup inválido.')}};$('#csv').onclick=()=>{let rows=[['Data','Situação','Entradas e saídas','Horas','Diária'],...entries().map(e=>[e.data,labels[e.status],e.intervals.map(i=>i.in+'-'+i.out).join(' | '),(worked(e)/60).toFixed(2),e.diaria])],txt='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\r\n');download(base('folha-de-ponto')+'.csv',txt,'text/csv;charset=utf-8')};$('#limpar').onclick=()=>{if(confirm('Apagar todos os dados?')){state={...seed,registros:[]};render()}};$('#imprimirContra').onclick=()=>{setTab('contracheque');print()};$('#imprimirPonto').onclick=()=>alert('Nesta versão independente, use Exportar CSV para a folha de ponto ou imprima a tela pelo navegador.');
let swipe={};$('#app').ontouchstart=e=>swipe={x:e.touches[0].clientX,y:e.touches[0].clientY,blocked:!!e.target.closest('input,button,select,dialog')};$('#app').ontouchend=e=>{if(swipe.blocked)return;let dx=e.changedTouches[0].clientX-swipe.x,dy=e.changedTouches[0].clientY-swipe.y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.3){let t=['jornada','contracheque','configuracoes'],i=t.indexOf(tab);setTab(t[Math.max(0,Math.min(2,i+(dx<0?1:-1)))])}};render();
function readImage(file,key){if(!file)return;if(!file.type.startsWith('image/')||file.size>3*1024*1024){alert('Escolha uma imagem de até 3 MB.');return}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);state[key]=canvas.toDataURL('image/webp',.86);render()};img.src=String(reader.result)};reader.readAsDataURL(file)}
$('#fotoFuncionario').onchange=e=>{readImage(e.target.files[0],'funcionarioImagem');e.target.value=''};$('#layoutEmpresa').onchange=e=>{readImage(e.target.files[0],'empresaImagem');e.target.value=''};
$$('[data-image-prop]').forEach(el=>el.oninput=e=>{const key=e.target.dataset.imageProp;state[key]=e.target.type==='range'?+e.target.value:e.target.value;render()});$$('[data-remove-image]').forEach(btn=>btn.onclick=()=>{state[btn.dataset.removeImage+'Imagem']='';render()});
const crop={type:'',image:null,zoom:100,x:0,y:0,drag:false,lastX:0,lastY:0};
function cropDimensions(type){return type==='funcionario'?{width:800,height:1000}:{width:1600,height:500}}
function drawCrop(){if(!crop.image)return;const canvas=$('#cropCanvas'),ctx=canvas.getContext('2d'),base=Math.max(canvas.width/crop.image.width,canvas.height/crop.image.height),scale=base*crop.zoom/100,w=crop.image.width*scale,h=crop.image.height*scale,maxX=Math.max(0,(w-canvas.width)/2),maxY=Math.max(0,(h-canvas.height)/2);crop.x=Math.max(-maxX,Math.min(maxX,crop.x));crop.y=Math.max(-maxY,Math.min(maxY,crop.y));ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(crop.image,(canvas.width-w)/2+crop.x,(canvas.height-h)/2+crop.y,w,h)}
function openCrop(type){const src=state[type+'Imagem'];if(!src){alert('Escolha uma imagem antes de recortar.');return}const canvas=$('#cropCanvas'),size=cropDimensions(type),img=new Image();canvas.width=size.width;canvas.height=size.height;crop.type=type;crop.zoom=100;crop.x=0;crop.y=0;$('#cropZoom').value='100';$('#cropZoomOutput').value='100%';img.onload=()=>{crop.image=img;drawCrop();$('#cropModal').showModal()};img.src=src}
function centerImage(type){state[type+'X']=50;state[type+'Y']=50;state[type+'Zoom']=100;state[type+'Fit']=type==='empresa'?'contain':'cover';render()}
$$('[data-crop-image]').forEach(btn=>btn.onclick=()=>openCrop(btn.dataset.cropImage));$$('[data-center-image]').forEach(btn=>btn.onclick=()=>centerImage(btn.dataset.centerImage));
$('#cropZoom').oninput=e=>{crop.zoom=+e.target.value;$('#cropZoomOutput').value=crop.zoom+'%';drawCrop()};$('#cropCenter').onclick=()=>{crop.x=0;crop.y=0;crop.zoom=100;$('#cropZoom').value='100';$('#cropZoomOutput').value='100%';drawCrop()};
const cropCanvas=$('#cropCanvas');cropCanvas.onpointerdown=e=>{crop.drag=true;crop.lastX=e.clientX;crop.lastY=e.clientY;cropCanvas.setPointerCapture(e.pointerId)};cropCanvas.onpointermove=e=>{if(!crop.drag)return;const rect=cropCanvas.getBoundingClientRect();crop.x+=(e.clientX-crop.lastX)*cropCanvas.width/rect.width;crop.y+=(e.clientY-crop.lastY)*cropCanvas.height/rect.height;crop.lastX=e.clientX;crop.lastY=e.clientY;drawCrop()};cropCanvas.onpointerup=cropCanvas.onpointercancel=()=>crop.drag=false;
$('#cropApply').onclick=()=>{const key=crop.type+'Imagem';state[key]=$('#cropCanvas').toDataURL('image/webp',.9);state[crop.type+'Fit']='cover';state[crop.type+'Zoom']=100;state[crop.type+'X']=50;state[crop.type+'Y']=50;$('#cropModal').close();render()};
})();
